### ISSUE TITLE
Improve user navigation for mobile devices

### ISSUE THREAD

**Issue by nujovich** [aditya-singh9/v2#3]
Currently, the application content is not appealing to users when width and height are reduced on mobile devices

![image](https://user-images.githubusercontent.com/48018975/192551655-678cb888-bd55-481d-933c-85f54e5bc195.png)

**Comment by nujovich** [comment]
Hi @aditya-singh9 can I work on this issue ?

**Comment by aditya-singh9** [comment]
Sure.

I will assign it to you
