### ISSUE TITLE
a custom 404 error page

### ISSUE THREAD

**Issue by aditya-singh9** [aditya-singh9/v2#4]
The 404 error page should open when the keywords after the domain is unrecognised or the link do not exists.
Example:
When a user visits
https://www.adityasingh.tech/fhdjsbdh

The user should see that custom 404 error page.

**Comment by petesfrench** [comment]
Hi @aditya-singh9, I would like to work on this issue! Do you know what you would like the page to look like?

**Comment by aditya-singh9** [comment]
As of now, i do not have any ideas but the page should have the link of original website so that users can go to the correct website.
You can make the webpage look like the way you want. Just keep the color scheme in mind.

**Comment by aditya-singh9** [comment]
Do you want to work on this?

**Comment by petesfrench** [comment]
I have made a PR [here](https://github.com/aditya-singh9/v2/pull/5), I have applied the style present on the rest of the page but left it fairly simple so you can get it the way you want it.
